# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
      - main
      - azure-pipelines

pr: none

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'
  version: 0.1-SNAPSHOT

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              APP_REVISION="master-$(Build.SourceVersion)"
              echo "##vso[task.setvariable variable=APP_REVISION]${APP_REVISION}"
              echo "Generated Docker tag: ${APP_REVISION}"
            displayName: 'Generate Docker tag'
#          - task: Maven@3
#            inputs:
#              mavenPomFile: 'pom.xml'
#              goals: 'clean install'
#              publishJUnitResults: false
#              javaHomeOption: 'JDKVersion'
#              jdkVersionOption: '1.11'
#              mavenVersionOption: 'Default'
#              mavenAuthenticateFeed: false
#              effectivePomSkip: false
#              sonarQubeRunAnalysis: false'
          - task: Docker@2
            displayName: Build analytics API image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/.azure/resources/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/target/'
              arguments: --build-arg VERSION=$(version)
              tags: |
                $(tag)
          - task: Docker@2
            displayName: Push analytics API image
            inputs:
              command: push
              dockerfile: '$(Build.SourcesDirectory)/.azure/resources/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/target/'
              arguments: --build-arg VERSION=$(version)
              tags: |
                $(tag)
