# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  tags:
    include:
    - v*

pr: none

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'
  CONTAINER_REGISTRY: docker.io
  CONTAINER_REGISTRY_CON: ruks-docker-registry
  ANALYTICS_REPOSITORY: ruks/analytics-api

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo Hello, world on tag release!
            displayName: 'Run a one-line script'
          - task: AzureCLI@1
            displayName: 'Generate kube config'
            inputs:
              azureSubscription: 'azure-cli'
              scriptLocation: inlineScript
              inlineScript: 'az aks get-credentials --resource-group APIM-RnD-RG --name apimanalytics --admin'            
