# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

pr: none

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'
  CONTAINER_REGISTRY: docker.io
  CONTAINER_REGISTRY_CON: ruks-docker-registry
  ANALYTICS_REPOSITORY: ruks/analytics-api

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'
