# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
      - main
      - azure-pipelines

pr: none

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
#          - task: Maven@3
#            inputs:
#              mavenPomFile: 'pom.xml'
#              goals: 'clean install'
#              publishJUnitResults: false
#              javaHomeOption: 'JDKVersion'
#              jdkVersionOption: '1.11'
#              mavenVersionOption: 'Default'
#              mavenAuthenticateFeed: false
#              effectivePomSkip: false
#              sonarQubeRunAnalysis: false'
#          - task: CopyFiles@2
#            inputs:
#              contents: '$(Build.SourcesDirectory)/target/org.wso2.choreo.analytics.api-0.1-SNAPSHOT.jar'
#              targetFolder: '$(Build.SourcesDirectory)/.azure/resources/target'
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/.azure/resources/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/target/'
              tags: |
                $(tag)
