# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
    - refs/tags/*

pr: none

variables:
  tag: '$(Build.BuildId)'
  CONTAINER_REGISTRY: docker.io
  CONTAINER_REGISTRY_CON: ruks-docker-registry
  ANALYTICS_REPOSITORY: ruks/analytics-api

steps:
- script: echo Hello, world on tag release! $(Build.SourceVersion) $(Build.SourceBranch)
  displayName: 'Run a one-line script'
