# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
      - main
      - azure-pipelines

pr: none

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'
  CONTAINER_REGISTRY: apimAnalyticsApi
  ANALYTICS_REPOSITORY: choreoapim/analytics-api

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # - task: Maven@3
          #   inputs:
          #     mavenPomFile: 'pom.xml'
          #     goals: 'clean install'
          #     publishJUnitResults: false
          #     javaHomeOption: 'JDKVersion'
          #     jdkVersionOption: '1.11'
          #     mavenVersionOption: 'Default'
          #     mavenAuthenticateFeed: false
          #     effectivePomSkip: false
          #     sonarQubeRunAnalysis: false'
          - task: Docker@2
            displayName: Build analytics API image
            inputs:
              command: build
              containerRegistry: $(CONTAINER_REGISTRY)
              repository: $(ANALYTICS_REPOSITORY)
              dockerfile: '$(Build.SourcesDirectory)/.azure/resources/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/target/'
              tags: |
                $(tag)
          - task: Docker@2
            displayName: Build analytics API image
            inputs:
              command: push
              containerRegistry: $(CONTAINER_REGISTRY)
              repository: $(ANALYTICS_REPOSITORY)
              dockerfile: '$(Build.SourcesDirectory)/.azure/resources/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/target/'
              tags: |
                $(tag)
