# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  tags:
    include:
      - "*"

pr: none

variables:
  tag: '$(Build.BuildId)'
  CONTAINER_REGISTRY: docker.io
  CONTAINER_REGISTRY_CON: ruks-docker-registry
  ANALYTICS_REPOSITORY: ruks/analytics-api

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              APP_REVISION="$(Build.SourceBranchName)"
              echo "##vso[task.setvariable variable=APP_REVISION]${APP_REVISION}"
              echo "Generated Docker tag: ${APP_REVISION}"
            displayName: 'Generate Docker tag'
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean install'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false'
          - task: Docker@2
            displayName: Build analytics API image
            inputs:
              command: build
              containerRegistry: $(CONTAINER_REGISTRY_CON)
              repository: $(ANALYTICS_REPOSITORY)
              dockerfile: '$(Build.SourcesDirectory)/.azure/resources/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/target/'
              tags: |
                latest
                $(APP_REVISION)
          - task: Docker@2
            displayName: Push analytics API image
            inputs:
              command: push
              containerRegistry: $(CONTAINER_REGISTRY_CON)
              repository: $(ANALYTICS_REPOSITORY)
              dockerfile: '$(Build.SourcesDirectory)/.azure/resources/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/target/'
              tags: |
                latest
                $(APP_REVISION)
#          - script: |
#              curl -v --header "Content-Type: application/json" \
#              --request POST \
#              --data '{ "newDockerImage" : "$(CONTAINER_REGISTRY)/$(ANALYTICS_REPOSITORY):$(APP_REVISION)"}' \
#              https://dev.azure.com/amilad0698/_apis/public/distributedtask/webhooks/analyticsapidev?api-version=6.0-preview
#            displayName: 'Trigger dev image tag updating build'

