# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
    - refs/tags/*

pr: none

variables:
  tag: '$(Build.BuildId)'
  CONTAINER_REGISTRY: docker.io
  CONTAINER_REGISTRY_CON: ruks-docker-registry
  ANALYTICS_REPOSITORY: ruks/analytics-api

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build  
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo Hello, world on tag release!
            displayName: 'Run a one-line script'
          - task: Docker@2
            displayName: Login to Docker Hub
            inputs:
              command: login
              containerRegistry: analytics-api-csr
