openapi: 3.0.1
info:
  title: AnalyticsRestAPI
  description: |
    This is a RESTFul API for Analytics graphQL api.
  contact:
    name: Rukshan
    url: https://www.rukspot.com
    email: rukshan@wso2.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://analytics.choreo.wso2.com
paths:
  /query:
    post:
      description: Create a new Order
      parameters:
        - in: header
          name: Environment
          schema:
            type: string
          required: true
      requestBody:
        description: Order object that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputQuery'
        required: true
      responses:
        200:
          description: Server responsded graphQL response
          headers:
            Location:
              description: The URL of the newly created resource.
              schema:
                type: string
            Content-Type:
              description: The content type of the body.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
      security:
        - bearerAuth: []
      x-codegen-request-body-name: body
components:
  schemas:
    Result:
      title: Result
      type: object
      properties:
        errors:
          type: object
        data:
          type: object
    InputQuery:
      title: InputQuery
      required:
        - query
      type: object
      properties:
        query:
          type: string
        variables:
          type: object
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
