analytics:
  datasource:
    username: admin
    password: admin
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://analytics-apim.database.windows.net:1433;database=testdb
  kusto:
    clientid: ssdfdsfdsfsdfsdfsd
    pass: sdfsdfdsfefsdfdsf
    auth: sdfdfsdfdsfsdf
    url: http://localhost:9090
    database: testdvb
  security:
#    trustStore: /Users/rukshan/wso2/apim/coreo/wso2is-5.10.0/repository/resources/security/client-truststore.jks
#    trustStorePass: wso2carbon
    jwks: https://localhost:9444/oauth2/jwks
    jwksIssuer: https://localhost:9444:443/oauth2/token
