analytics:
  datasource:
    username: admin
    password: admin
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=analytics
  kusto:
    clientid: 34c4062d-3588-4426-a6e1-de1fc88fb8a3
    pass: 9cf4fdb3-ec1f-406a-808e-acd33c9e390a
    auth: 2b367c99-e2d6-4259-8cc7-d62a110d678f
    url: https://localhost:9099/query
    database: analytics
  security:
    #    trustStore: /Users/rukshan/wso2/apim/coreo/wso2is-5.10.0/repository/resources/security/client-truststore.jks
    #    trustStorePass: wso2carbon
    jwks: https://localhost:9443/oauth2/jwks
    jwksIssuer: https://localhost:9443/oauth2/token
