/** Generated by the default template from graphql-java-generator */
package org.wso2.choreo.analytics.api;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.wso2.choreo.analytics.api.config.APIConfiguration;
import org.wso2.choreo.analytics.api.config.ConfigHolder;

import javax.annotation.PostConstruct;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@SpringBootApplication(scanBasePackages = { "org.wso2.choreo.analytics.api", "com.graphql_java_generator" ,
		"org.wso2.choreo.analytics.api" })
@EnableJpaRepositories(basePackages = { "org.wso2.choreo.analytics.api", "com.graphql_java_generator" ,
		"org.wso2.choreo.analytics.api" })
@EntityScan(basePackages = { "org.wso2.choreo.analytics.gql", "com.graphql_java_generator" ,"org.wso2.choreo.analytics.gql" })
@EnableConfigurationProperties
@EnableCaching(proxyTargetClass = true)
public class AnalyticsApplication {

	@Autowired
	private APIConfiguration configuration;

	@PostConstruct
	void postConstruct() {
		ConfigHolder.getInstance().setConfiguration(configuration);
		if (configuration.getSecurity().getTrustStore() != null
				&& configuration.getSecurity().getTrustStorePass() != null) {
			System.setProperty("javax.net.ssl.trustStore", configuration.getSecurity().getTrustStore());
			System.setProperty("javax.net.ssl.trustStorePassword", configuration.getSecurity().getTrustStorePass());
		}

	}
	public static void main(String[] args) {
		SpringApplication.run(AnalyticsApplication.class, args);
	}
}
